# Generated by Django 5.1.4 on 2025-01-06 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('cm_hours', models.IntegerField()),
                ('td_hours', models.IntegerField()),
                ('tp_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plage', models.CharField(max_length=2)),
                ('semestre', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.module')),
            ],
            options={
                'unique_together': {('plage', 'semestre', 'day')},
            },
        ),
    ]
