# Generated by Django 5.1.4 on 2024-12-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('cm_hours', models.IntegerField()),
                ('td_hours', models.IntegerField()),
                ('tp_hours', models.IntegerField()),
            ],
        ),
    ]
