# Generated by Django 5.1.4 on 2024-12-27 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plage', models.CharField(max_length=2)),
                ('semestre', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('modulde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.module')),
            ],
            options={
                'unique_together': {('plage', 'semestre', 'day')},
            },
        ),
    ]
